/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/components/business/AuthForm.vue')['default']
    ContextMenu: typeof import('./src/components/contextMenu/ContextMenu.vue')['default']
    CreateTeamModal: typeof import('./src/components/business/CreateTeamModal.vue')['default']
    FileContextMenu: typeof import('./src/components/contextMenu/FileContextMenu.vue')['default']
    FilePreviewWindow: typeof import('./src/components/WindowManager/FilePreviewWindow.vue')['default']
    FilePropertiesModal: typeof import('./src/components/business/FilePropertiesModal.vue')['default']
    FreeDialog: typeof import('./src/components/freeDialog/index.vue')['default']
    ImagePreview: typeof import('./src/components/WindowManager/ImagePreview.vue')['default']
    InviteMemberModal: typeof import('./src/components/business/InviteMemberModal.vue')['default']
    Menu: typeof import('./src/components/menu-ui/Menu.vue')['default']
    PDFPreview: typeof import('./src/components/WindowManager/PDFPreview.vue')['default']
    PermissionSelector: typeof import('./src/components/business/PermissionSelector.vue')['default']
    ResizableWindow: typeof import('./src/components/WindowManager/ResizableWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/menu-ui/SubMenu.vue')['default']
    TaskBar: typeof import('./src/components/WindowManager/TaskBar.vue')['default']
    UpdatePermissionModal: typeof import('./src/components/business/UpdatePermissionModal.vue')['default']
    VideoPreview: typeof import('./src/components/WindowManager/VideoPreview.vue')['default']
    WindowManager: typeof import('./src/components/WindowManager/WindowManager.vue')['default']
  }
}
